[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | \.local
  | \.cache
  | cache
  | build
  | _build
  | dist
)/
'''
